#!/bin/bash
output="`basename --suffix .mol2 $1`singlechainscript.sh"
sed "s/{input}/$(basename --suffix=.mol2 "$1")/g" templatesingle.slurm > "$output"
output2="`basename --suffix .mol2 $1`bulkscript.sh"
sed "s/{input}/$(basename --suffix=.mol2 "$1")/g" templatebulk.slurm > "$output2"
output3="`basename --suffix .mol2 $1`template.minimize"
sed "s/{input}/$(basename --suffix=.mol2 "$1")/g" template.minimize > "$output3"
output4="`basename --suffix .mol2 $1`template.equil"
sed "s/{input}/$(basename --suffix=.mol2 "$1")/g" template.equil > "$output4"
output5="`basename --suffix .mol2 $1`template.bulk"
sed "s/{input}/$(basename --suffix=.mol2 "$1")/g" template.bulk > "$output5"
